### ISSUE TITLE
Please add flush_output/0 after the write of the prompt.

### ISSUE THREAD

**Issue by psilord** [RyanBurnside/PrologPRS#1]
Please add a:

`flush_output,`

after the `write` line. This will make it such the prompt appears properly when running in swipl.

Thank you!

**Comment by psilord** [comment]
Ah apparently, this problem exists in 7.6.4 swipl, but the current version is 9.1.12. I updated to the current version and the problem went away.

**Comment by RyanBurnside** [comment]
Ok, thanks.
I'd prefer to keep the code short - seems like a bug in 7.6.4.
